// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Particle, SmokeParticle, imageLoaded, imageObj, _ref;
  Particle = require('../../core/Particle');
  imageObj = new Image();
  imageLoaded = false;
  imageObj.onload = function() {
    return imageLoaded = true;
  };
  imageObj.src = "../../../img/smoke.png";
  return SmokeParticle = (function(_super) {
    __extends(SmokeParticle, _super);

    function SmokeParticle() {
      _ref = SmokeParticle.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SmokeParticle.prototype.render = function(ctx) {
      ctx.save();
      if (imageLoaded) {
        ctx.drawImage(imageObj, this.pos.x - 128, this.pos.y - 128);
        if (!showCenter) {
          return;
        }
      }
      ctx.fillStyle = "rgba(255, 0, 0, 1)";
      ctx.translate(this.pos.x, this.pos.y);
      ctx.beginPath();
      ctx.arc(0, 0, 5, 0, Math.PI * 2, true);
      ctx.closePath();
      ctx.fill();
      return ctx.restore();
    };

    return SmokeParticle;

  })(Particle);
});
