// Generated by CoffeeScript 1.6.3
define(function(require) {
  var ChanmberBox;
  return ChanmberBox = (function() {
    function ChanmberBox(x1, y1, x2, y2) {
      this.x1 = x1;
      this.y1 = y1;
      this.x2 = x2;
      this.y2 = y2;
    }

    ChanmberBox.prototype.apply = function(particle) {
      if (particle.pos.x - particle.size < this.x1 || particle.pos.x + particle.size > this.x2) {
        particle.velocity.x = -particle.velocity.x;
      }
      if (particle.pos.y - particle.size < this.y1 || particle.pos.y + particle.size > this.y2) {
        return particle.velocity.y = -particle.velocity.y;
      }
    };

    return ChanmberBox;

  })();
});
