// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Particle, SnowParticle, _ref;
  Particle = require('../../core/Particle');
  return SnowParticle = (function(_super) {
    __extends(SnowParticle, _super);

    function SnowParticle() {
      _ref = SnowParticle.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SnowParticle.prototype.render = function(ctx) {
      var gradient;
      ctx.save();
      ctx.translate(this.pos.x, this.pos.y);
      gradient = ctx.createRadialGradient(0, 0, 0, 0, 0, this.size);
      gradient.addColorStop(0, "rgba(255, 255, 255, 0.9)");
      gradient.addColorStop(0.5, "rgba(255, 255, 255, 0.5)");
      gradient.addColorStop(1, "rgba(255, 255, 255, 0)");
      ctx.fillStyle = gradient;
      ctx.beginPath();
      ctx.arc(0, 0, this.size, 0, Math.PI * 2, true);
      ctx.closePath();
      ctx.fill();
      return ctx.restore();
    };

    return SnowParticle;

  })(Particle);
});
