// Generated by CoffeeScript 1.6.3
define(function(require) {
  var SnowEffector;
  return SnowEffector = (function() {
    function SnowEffector() {}

    SnowEffector.prototype.apply = function(particle) {
      particle.velocity.x += (1 - Math.random() * 2) / 10;
      if (particle.pos.x > window.innerWidth || particle.pos.y > window.innerHeight) {
        return particle.age = particle.life;
      }
    };

    return SnowEffector;

  })();
});
