// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function(require) {
  var Particle, SnowParticle, _ref;
  Particle = require('../../core/Particle');
  return SnowParticle = (function(_super) {
    __extends(SnowParticle, _super);

    function SnowParticle() {
      _ref = SnowParticle.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SnowParticle.prototype.render = function(ctx) {
      var alpha, scale;
      scale = alpha = (1 - this.age / this.life).toFixed(2);
      ctx.save();
      ctx.fillStyle = "rgba(" + this.color.r + ", " + this.color.g + ", " + this.color.b + ", " + alpha + ")";
      ctx.translate(this.pos.x, this.pos.y);
      ctx.beginPath();
      ctx.arc(0, 0, this.size, 0, Math.PI * 2, true);
      ctx.closePath();
      ctx.fill();
      return ctx.restore();
    };

    return SnowParticle;

  })(Particle);
});
